from __future__ import annotations

import shutil
from pathlib import Path
from typing import Protocol
from uuid import uuid4

from adapters.patch_cpp.compiler import compile_stub
from adapters.patch_cpp.injector import inject_stub
from adapters.patch_cpp.log_reader import read_stub_logs


class PatchPrototypeEngine(Protocol):
    def create_project(self, strategy: dict) -> dict: ...
    def compile_project(self, project_path: str) -> dict: ...
    def inject(self, dll_path: str, pid: int) -> dict: ...
    def collect_logs(self, project_path: str) -> list[dict]: ...


class StubPatchPrototypeEngine:
    def __init__(self, workspace: str = "data/generated_patches", template_root: str = "templates/minhook_dll") -> None:
        self.workspace = Path(workspace)
        self.template_root = Path(template_root)

    def create_project(self, strategy: dict) -> dict:
        project_name = f"patch_{uuid4().hex[:8]}"
        project_path = self.workspace / project_name
        project_path.mkdir(parents=True, exist_ok=True)

        if self.template_root.exists():
            shutil.copytree(self.template_root, project_path / "template", dirs_exist_ok=True)

        (project_path / "README.txt").write_text(
            "Stub patch project generated by RE Harness.\n"
            f"Method: {strategy.get('method', 'hook')}\n"
            f"Target: {strategy.get('target_addr', 'unknown')}\n",
            encoding="utf-8",
        )
        return {"ok": True, "project_path": str(project_path)}

    def compile_project(self, project_path: str) -> dict:
        return compile_stub(project_path)

    def inject(self, dll_path: str, pid: int) -> dict:
        return inject_stub(dll_path, pid)

    def collect_logs(self, project_path: str) -> list[dict]:
        return read_stub_logs(project_path)
